[global]
no-cache-dir = true
index-url = http://mirrors.baidubce.com/pypi/simple/
# index-url = http://pip.baidu.com/pypi/simple/
# extra-index-url =
#         http://pip.baidu.com/pypi/simple/
[install]
trusted-host =
        mirrors.baidubce.com
        # pip.baidu.com